name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # 仅当推送 v 开头的 Tag 时触发（如 v1.0.0）

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # 允许推送镜像到 GHCR
      contents: read   # 允许读取仓库代码

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动生成的 Token，无需手动配置

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/colin9959/minfo:${{ env.VERSION }}
            ghcr.io/colin9959/minfo:latest